server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/startupcrm_db?options=-c%20timezone=UTC
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    com.crm: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

app:
  jwt:
    secret: crm-secret-key-change-in-production-2026
    expiration: 86400000
